name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  validate:
    name: 1. Validar Calidad del Código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v3

      - name: Iniciar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar Dependencias
        run: npm install

      - name: Ejecutar Pruebas
        run: npm run test